- more updates
Changed files:
    EMCpower-init.patch -> 1.6

diff --git a/EMCpower-init.patch b/EMCpower-init.patch
--- a/EMCpower-init.patch
+++ b/EMCpower-init.patch
@@ -1,4 +1,4 @@
---- EMCpower-5.0.0/PowerPath~	2007-02-07 10:06:21.000000000 +0200
+--- EMCpower-5.0.0/PowerPath~	2006-09-04 16:10:03.000000000 +0300
 +++ EMCpower-5.0.0/PowerPath	2006-09-04 16:10:03.000000000 +0300
 @@ -15,6 +15,9 @@
  
@@ -23,7 +23,35 @@
                ;;
          esac
      fi
-@@ -106,19 +109,19 @@
+@@ -69,27 +72,9 @@
+ # the following are the internationalization specific lines
+-
+-if [ ! -x /usr/bin/gettext ]; then
+-gettext()
+-{
+- echo $*
+-}
+-eval_gettext()
+-{
+- eval "echo $*"
+-}
+-
+-else
+-. gettext.sh
+ TEXTDOMAIN=PowerPath
+ export TEXTDOMAIN
+-TEXTDOMAINDIR=$PPBASE/i18n/catalog
+-
+-export TEXTDOMAINDIR
+ export RPM_INSTALL_PREFIX
+-fi
+ # end of internationalization
+ 
+-
+ pp_stop_lvm()
+ {
+     if test -x /sbin/vgchange -a -x /sbin/vgscan ; then
+@@ -106,19 +91,19 @@
                          err_stop=`/sbin/vgchange -a n $i  2>&1 | grep "open logical volume"`
                          if [ "$err_stop" != "" ]; then
                                  if [ "$open_vol" = "" ]; then
@@ -47,7 +75,7 @@
  	return 1
          fi
   return 0
-@@ -154,9 +157,9 @@
+@@ -154,9 +139,9 @@
      rc_check
  
      if rc_status ; then
@@ -59,7 +87,7 @@
      fi
  }
  
-@@ -166,8 +169,8 @@
+@@ -166,7 +151,7 @@
  {
      if [ -f /etc/emcp_devicesDB.dat ]; then 
          if [ -f /etc/emcp_devicesDB.idx ]; then
@@ -68,8 +96,7 @@
              rc_check
          fi
      fi
- 
-@@ -206,10 +209,10 @@
+@@ -206,9 +191,9 @@
  
      /sbin/powermt load		> /dev/null 2>&1
      rc_check
@@ -81,9 +108,7 @@
      /sbin/powermt save		> /dev/null 2>&1
      rc_check
      /sbin/powermt register	> /dev/null 2>&1
-     rc_check
-@@ -224,14 +227,14 @@
- {
+@@ -225,13 +210,13 @@
      ps -C naviagent >> /dev/null
      if [ $? -eq 0 ]; then
 -        echo "`eval_gettext \"Navisphere agent is running.\"`"
@@ -101,16 +126,14 @@
 +        echo "`eval nls \"Please stop powermt and then re-issue \\$script_name stop.\"`"
          return 1
      fi
-@@ -260,6 +263,6 @@
-         /sbin/modprobe -q -s --first-time $d
+@@ -261,5 +246,5 @@
          rc_check
          if [ $? -ne 0 ] ; then
 -            echo "`eval_gettext \"PowerPath could not load module \\$d\"`"
 +            echo "`eval nls \"PowerPath could not load module \\$d\"`"
              break
          fi
-@@ -288,8 +291,8 @@
- 
+@@ -289,7 +274,7 @@
  case "$1" in
      start)
  
@@ -119,7 +142,7 @@
  
          ###
          # Start the 32-bit emulation for ia64
-@@ -411,7 +414,7 @@
+@@ -411,7 +396,7 @@
                      unload_drivers
                  fi
              else
@@ -128,7 +151,7 @@
                  unload_drivers
              fi
          fi
-@@ -419,11 +422,11 @@
+@@ -419,11 +404,11 @@
          ;;
  
      stop)
@@ -142,7 +165,7 @@
          else
              #
              # Tresspass can happen if new devices are added or some devices 
-@@ -436,9 +439,9 @@
+@@ -436,7 +421,7 @@
              if ok_to_stop; then
                  /sbin/powermt save > /dev/null 2>&1
                  rc_check
@@ -151,9 +174,12 @@
                  rc_check
                  /sbin/powermt remove dev=all 2> /var/tmp/.pp_exit
                  devr=$?
-                 cat /var/tmp/.pp_exit | grep "not found" > /dev/null 2>&1
-                 cdevs=$?
-@@ -477,7 +480,7 @@
+@@ -453,3 +438,3 @@
+                     if [ $? -ne 0 ] ; then
+-                        echo "`eval_gettext \"PowerPath could not unload PowerPath modules.\"`"
++						nls "PowerPath could not unload PowerPath modules."
+                     fi
+@@ -477,7 +462,7 @@
          ;;
      *)
          var=$0
